Update nwa12-ci

diff --git a/.github/workflows/NWA12-ci.yaml b/.github/workflows/NWA12-ci.yaml
--- a/.github/workflows/NWA12-ci.yaml
+++ b/.github/workflows/NWA12-ci.yaml
@@ -32,8 +32,27 @@ jobs:
     - name: Build MOM6SIS2
       run: |
         cd ${{ env.TEST_DIR }}/NWA12_CHECK/builds
-        ./linux-build.bash -m gaea -p ncrc5.intel23 -t repro -f mom6sis2
-
+        jobid=$(sbatch --parsable sbatch --clusters=es --nodes=1 --ntasks=8 --account=cefi --partition=eslogin_c5 --qos=normal --export=NONE ./linux-build.bash -m gaea -p ncrc5.intel23 -t repro -f mom6sis2 | awk -F';' '{print $1}' | cut -f1)
+        sleep 1
+          while :; do
+              job_status=$(squeue -h -j "$jobid" -o "%T" 2>/dev/null)
+              if [ -z "$job_status" ]; then
+                 echo "Job with ID $jobid is not found or completed."
+                 break
+              else
+                 echo "Job with ID $jobid is still running."
+                 echo "Job Status: $job_status"
+              fi
+              sleep 60  # Adjust the sleep duration as needed
+          done
+          #
+          check_file="${{ env.TEST_DIR }}/NWA12_CHECK/builds/build/gaea-ncrc5.intel23/ocean_ice/repro/MOM6SIS2"
+          if [ -f "$check_file" ]; then
+              echo "PASSED: $check_file"
+          else
+              echo "FAILED: $check_file"
+              exit 1
+          fi 
 
   run-NWA12-ci:
     needs: checkout-build
@@ -62,7 +81,7 @@ jobs:
           done
           # 
           expected_string="All restart files are identical, PASS"
-          check_file="${{ env.TEST_DIR }}/NWA12_CHECK/${{ matrix.case }}/NWA12.CFC_o.$jobid"
+          check_file="${{ env.TEST_DIR }}/NWA12_CHECK/exps/${{ matrix.case }}/NWA12.CFC_o.$jobid"
           if [ -f "$check_file" ]; then
              if grep -qF "$expected_string" $check_file; then
                  echo "PASSED: ${{ matrix.case }}"
